server:
  port: 8512

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/changing_classroom?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 451283..Qq
  application:
    name: service-user

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # nacos注册中心地址
        username: nacos
        password: nacos
        group: SEATA_GROUP

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml